### PR TITLE
Fixed undefined error message

### PR DESCRIPTION
**Pull request by ghost**
your approach is not working for me. I believe this is a typo?!

cheers,
lukas

### CODE REVIEW

**Comment by sualko** [comment]
Every property of <code>window</code> is also available in the global namespace, so that is why I am wondering why you get an undefined error. I tested successfully with FF 38 and 39.

Nonetheless this pr should be go to https://github.com/webrtc/adapter/, because modifying a bundle file is never a good idea. I leave this open, until your issue is fixed.

**Comment by ghost** [comment]
I used FF 39 too. But I have to change those lines otherwise the whole jsxc dependency file is not loaded probably. I'll check it again. cheers

**Comment by sualko** [comment]
Please post the response of <code>typeof mozRTCSessionDescription</code> in your js console.

**Comment by ghost** [comment]
untitled

**Comment by sualko** [comment]
Maybe an other library overwrites this variable. Can you test the above command on a neutral side like google?

**Comment by ghost** [comment]
I tested it on google.de

```
> window.RTCSessionDescription = mozRTCSessionDescription; console.debug("ping");
ReferenceError: mozRTCSessionDescription is not defined

> window.RTCSessionDescription = window.mozRTCSessionDescription; console.debug("ping");
undefined
"ping"
```

**Comment by sualko** [comment]
I am so happy that you could fix your issue, because I was worried that this could be a showstopper bug for the release today. :+1:

**Comment by ghost** [comment]
@sualko yup me too. I already wondered why that worked before :P

anyway can we move this and the otr repo to https://github.com/jsxc?
Would be nice if you could fork from the original source.
Cause I already wonder how your update process looks like.

Would be nice if we just pull from upstream in the future.

**Pull request closed without merging**
